### ISSUE TITLE
Need to define Gas Reward Order.

### ISSUE THREAD

**Issue by wanderer** [ethereum/yellowpaper#142]
In cases where where the coinbase is suiciding, the order in which the gas is rewarded to the coinbase and the suicide refund is given needs to specified.

**Comment by CJentzsch** [comment]
It is specified. The suicide happens after a single transaction. Here the suicide refund is only calculated and add the gas reward that will be given to the coinbase. The block reward (including the gas) is given at the very end if the execution of a block (see equation 4).

(Reopen if that was not clear or if you have another argument for why you think it is undefined)
