### ISSUE TITLE
Update # words in memory for CODECOPY, etc.?

### ISSUE THREAD

**Issue by Isweet** [ethereum/yellowpaper#168]
The definitions for instructions such as MSTORE have an explicit annotation specifying how \boldsymbol{\mu}_i (# words in memory) should change. However, for instructions such as CODECOPY, no such annotation exists. Is this an error?

Also, in the definition for SHA3, \boldsymbol{\mu}_i is changed, but there is no annotation specifying a write to memory. Why is this? Is this an error?

**Comment by pirapira** [comment]
Such an annotation has been added to CODECOPY.

SHA3 reads from the memory, so the counter is increased.

@Isweet Please close this issue if these answers are satisfactory.
