### ISSUE TITLE
Can we check the pdf into version control?

### ISSUE THREAD

**Issue by ebuchman** [ethereum/yellowpaper#180]
I link to the yellow paper all the time, but I'm not sure there's any more official link than http://gavwood.com/paper.pdf . Can we get the latest version checked into this repo? Or else get the ethereum organization to host it? Or put it on ipfs and post the latest hash in the readme, or something fun?

**Comment by Denton-L** [comment]
I think the best way would be to just get a Travis CI thing to auto-build and deploy, similar to ethereum/browser-solidity. Thoughts?

**Comment by terryburton** [comment]
Or consider http://github.com/terryburton/travis-github-release

**Comment by RichardLitt** [comment]
Putting the paper into IPFS and then putting the latest hash into the README would not be overly difficult. 

Here is the current hash, and a link to the gateway, for the paper as of just now: https://ipfs.io/ipfs/Qmcah7U5c8UhK6DWUJ5E9A2A67VZ1jpR1tZ8bf7PNjxVGy

**Comment by RichardLitt** [comment]
I'm happy to outline the steps for this, in the README in a PR, so that we can do this each time?
