### ISSUE TITLE
Parsing ambiguity in the `SMOD` specification

### ISSUE THREAD

**Issue by pirapira** [ethereum/yellowpaper#190]
In the table in Appendix H.2, `SMOD` is specified using an expression

```
sgn(μₛ[0]) |μₛ[0]| mod |μₛ[1]|
```

This is ambiguous because there are two possible parentheses around subexpressions

```
(sgn(μₛ[0]) |μₛ[0]|) mod |μₛ[1]|
```

or

```
sgn(μₛ[0]) (|μₛ[0]| mod |μₛ[1]|)
```

This difference affects the sign of the result.

**Comment by pirapira** [comment]
`(sgn(μₛ[0]) |μₛ[0]|) mod |μₛ[1]|` does not make sense because it's equivalent to shorter `μₛ[0] mod |μₛ[1]|`.  I opened a [pull-request](#191) to settle this.

**Comment by fulldecent** [comment]
This is merged in https://github.com/ethereum/yellowpaper/pull/191

This issue can be closed now.

**Comment by pirapira** [comment]
Thanks for pointing out.
