### ISSUE TITLE
Jump Destination Validity

### ISSUE THREAD

**Issue by channgo2203** [ethereum/yellowpaper#195]
Hello,

In the definition of the function D(c) = D_J(c,0), the second case D_J(c,i) = {i} \vee D_J(c,N(i,c[i])) if c[i] = JUMPDEST. In this case N(i,c[i]) always equals to (i + 1), thus D_J(c,i) = {i} \vee D_J(c,i+1)

I don't understand the statement: " must appera within the explicit defined portion of the code (rather than in the implicitly defined STOP operations that trail it)" As I understand, JUMPDEST must be before any STOP. I think it is not needed (JUMPDEST can be behind STOP).

**Comment by pirapira** [comment]
If you look up any position after the end of the code, that position implicitly contains a `STOP`.  Such implicit STOPs appear after the end of the code, while JUMPDEST must appear in the code.

The sentence does not talk about `STOP`s in the code, but about `STOP`s implicitly inserted after the end of the code.

**Comment by pirapira** [comment]
@channgo2203 please close the issue if my answer is OK.

**Comment by fulldecent** [comment]
This issue can be closed now.
