### ISSUE TITLE
Typo in (134)

### ISSUE THREAD

**Issue by toonn** [ethereum/yellowpaper#199]
Formula 134 has an opening bracket which seems to match with a closing parenthesis. I believe the opening bracket should be a parenthesis.
In the current revision this is defined on line 969:
https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L969

**Comment by pirapira** [comment]
This is not a typo.  `[x, y)` denotes the set of integers that are at least as large as `x` and smaller than `y`.

**Comment by toonn** [comment]
Thank you for commenting. Reading it again I can indeed see it's not a mistake. I blame my mistake on notation overload : )
