### ISSUE TITLE
Update gas spreadsheet

### ISSUE THREAD

**Issue by ethers** [ethereum/yellowpaper#205]
Can it be updated with the current gas costs?
https://docs.google.com/spreadsheets/d/1m89CVujrQe5LAFJ8-YAUCcNK950dUzMQPMJBxRtGCqs/edit#gid=0

Perhaps replace with updated values and leave the old value as a comment. Other suggestions are adding another column or tab?

There doesn't seem to be another repo that would be better to file this issue.

**Comment by fulldecent** [comment]
This issue is off topic. Please consider discussing on the Solidity Gitter.

This issue can be closed now.
