### ISSUE TITLE
Equations 1-2-3-4 need more concise reformulation

### ISSUE THREAD

**Issue by efaysal** [ethereum/yellowpaper#224]
Reading critically the equations 1-2-3-4, the time, t, is not expressed correctly. It's also very confusing by designing the same, t, for transactions and blocks to express the future state.

Given a transaction, the most powerful system, Gamma, will change locally the state at time, t, to state, t+1 ( assuming that Gamma process the transaction in one unit of time).
Processing the second  transaction, the most powerful system, Gamma, will change locally the state at time, t+1, to state, t+2.

Let's assume, we have, n transactions, state at time t+n+1 is defined. 

In equation (2), the time, t+1, refers to this time  t+n+1. Equation (4) should take into consideration the described process. 

All these elements will be introduced into the draft after a discussion?

**Comment by pirapira** [comment]
I think the variable `t` in (1) the variable `t` in (2) are not related.

**Comment by pirapira** [comment]
...but actually, `\sigma` takes an integer, and does this integer count blocks or transactions?

**Comment by efaysal** [comment]
Here you go, you are researching my point, keep looking into the equations, for sure it's confusing. 
The plain English in the draft is not reflected in the formulations. Many equations need to be reformulated to take into account some subtleties as the one we are discussion,  which time is reflected in sigma, transactions time or block time? 

I reformulated many of these equations but I need time to draft them ... may be next time.

**Comment by gavofyork** [comment]
in (1), `T` is a very general notion of "transaction" (as in CS literature, not as in Ethereum specifically) with `t` being temporal steps of such "transactions".

in (2-4), (1) is reformulated into something much better approximating what the Ethereum system is with the notional blocks and transactions.

as such (2-4) not being strictly derivable from (1), but rather a conceptual specialisation of (1) is very much on purpose. much of the value of these equations comes from their simplicity: this is the preamble and it's important to be able to describe concepts generally and concisely.
