### ISSUE TITLE
Ethereum Network Protocol: Authoritative Source?

### ISSUE THREAD

**Issue by Isweet** [ethereum/yellowpaper#236]
Just wondering if there is an authoritative, rigorous specification for the network (P2P) protocol used by Ethereum?

Something akin to the yellow paper would be great. Perhaps it can be added?

**Comment by fulldecent** [comment]
This seems to be addressed here: https://github.com/ethereum/yellowpaper/blob/master/Wire.tex

Is this what you were looking for?

**Comment by pirapira** [comment]
@Isweet is any of the answers satisfactory?

**Comment by Isweet** [comment]
Yes, my guess is that these will be enough. It would be nice if there was a canonical location, outside of a wiki, similar to: http://www.bittorrent.org/beps/bep_0003.html

Closing.
