### ISSUE TITLE
Ethereum whitepaper needs link update in bibliography

### ISSUE THREAD

**Issue by tbinetruy** [ethereum/yellowpaper#247]
Hi everyone,

I've just started reading the yellowpaper, and section "1.2 Previous Work" references to Vitalik's "Ethereum: a next generation smart contract and decentralized application platform". 

In the bibliography, the link to Vitalik's paper is "http://ethereum.org/ethereum.html". This page redirects me to ethereum.org instead of the paper itself which I assume is this one: https://github.com/ethereum/wiki/wiki/White-Paper

I think it would be useful to future readers that this URL is updated to the current one as to make it easier to find Vitalik's document.

Or is a bibliography supposed to show URL from where the document was retrieved rather than URL of where the document currently lives ?

Sincerely yours,

Thomas

**Comment by pirapira** [comment]
@tbinetruy yes, I think your point stands.

**Comment by pirapira** [comment]
@tbinetruy can you file a pull-request?

**Comment by tbinetruy** [comment]
sorry for the late reply.

Will do either today or tomorrow ;)

**Comment by pirapira** [comment]
Meaow.  I'll do this.
