### ISSUE TITLE
RLP-Rb coding, why breaking one byte into two conditions?

### ISSUE THREAD

**Issue by efaysal** [ethereum/yellowpaper#255]
In Formally, we define Rb ... It starts with:
 if the byte has a value less than 128 and so on.

What is the scientific reason to break one byte into two conditions: as its value is less than 128 or not. 

It may be more adequate to RLP-encoding one byte without going through that process, breaking down a byte into two conditions?

All current languages can handle or store one byte what ever is its intrinsic value. 

The current RLP coding is storing one byte as one byte if its intrinsic value is less than 128 and into two bytes if its value is greater than 128! 

126 will be stored as one byte, for instance 01111110 (126) 
212 will be stored as (242+1).242, for instance 11110011.11110010 (243).(242). 

What is the scientific reason?

**Comment by pirapira** [comment]
The reasons are the following two requirements:

* the encoding needs to store some small one-byte sequences as one byte
* the encoding needs to indicate if it uses one byte or more, in the first byte

though they are not scientific.

**Comment by efaysal** [comment]
Thanks, I will post my point soon.

**Comment by fulldecent** [comment]
This issue can be closed now.
