### ISSUE TITLE
Specify zero-th power of zero

### ISSUE THREAD

**Issue by pirapira** [ethereum/yellowpaper#257]
`0 ^ 0` might be zero or one.  So, the specification of `EXP` needs to decide the result of `EXP` on two zeros.

**Comment by efaysal** [comment]
It looks as indeterminate. However doing some Mathematics, 
it turns to be well definite with a real value which is 1. 

lim x^x when x --> 0 is equivalent to lim exp(xlog(x))  when x --> 0.

As lim xlog(x) when x -->0, is 0. 

lim x^x when x --> 0 is simply exp(0) = 1. 

0 ^ 0 better to expressed as 1. 

If you decide that 0 ^ 0=1, Mathematics are supporting you totally. 
Now it's better to assess if that convention is the suitable to be coded into the software ...

**Comment by chriseth** [comment]
You are giving an analytical explanation for an algebraic question. Note that the EVM does not know whether there is anything between 0 and 1 :-)

**Comment by efaysal** [comment]
I'm aware about that situation, that's why I finished my text with:

Now it's better to assess if that convention is the suitable to be coded into the software or VM. 

Agreed!

**Comment by efaysal** [comment]
FYI: 0^0 is still almost always defined as 1.0, as mandated by the IEEE 754 floating point standard.

**Comment by axic** [comment]
From a practical standpoint, both Solidity's internal constant evaluator and ethereumjs-vm (remix) consider it as 1.

**Comment by axic** [comment]
@winsvega can you add a test to the official suite for `EXP(0,0) == 1`?
