### ISSUE TITLE
Features with unlimited size byte array

### ISSUE THREAD

**Issue by efaysal** [ethereum/yellowpaper#280]
Couple of data have been defined as unlimited size byte array, Ti,Td and so on.
It's fine there is no issue in that. 

I wonder if someone did any statistics for  the current  observed Ti,Td  in the database?

This may help me the shape a second point I'm working on it to improve an Equation in YP.

**Comment by fulldecent** [comment]
This issue seems out of scope for this repository. Please consider moving to mailing lists.
