### ISSUE TITLE
French branch 

### ISSUE THREAD

**Issue by kurthalex** [ethereum/yellowpaper#284]
Is it possible to create a french branch in order to merge it with ours ? It contains the french translation 
https://github.com/asseth/yellowpaper/tree/french

**Comment by Apercu** [comment]
You should be able to create a PR onto a new branch `french`

**Comment by fulldecent** [comment]
Oh, hell no! This repo has enough issues and has way too many things changing.

I hope that translations can be explicitly ruled as OUT OF SCOPE for this repo until it is mature.

**Comment by nicksavers** [comment]
@kurthalex Is this still maintained? If you open a PR with a link in the README to the repository containing the French translation, I can merge it.

**Comment by kurthalex** [comment]
Ok thanks, will do it
