### ISSUE TITLE
What is the c() function in appendix D?

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/yellowpaper#294]
I can't see where the function `c` is defined in Appendix D. Where is it formally defined?

<img width="635" alt="screen shot 2017-04-12 at 13 20 40" src="https://cloud.githubusercontent.com/assets/731743/24957218/ea4cc3ac-1f82-11e7-81c4-4486311ef204.png">

**Comment by pirapira** [comment]
It is defined in (180) (which is just before subsection D.1 "Trie Database").

**Comment by JustinDrake** [comment]
Oh I see, thanks 👍  A bit confusing to have the definition quite a way below its first use.

**Comment by pirapira** [comment]
I agree.
