### ISSUE TITLE
A typo in eq (77) ?

### ISSUE THREAD

**Issue by rtkaczyk** [ethereum/yellowpaper#299]
[Equation (77)](https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L623) refers to gas remaining, `g'`, rather than the amount to be refunded, `g*`. 

Should this be changed to:

```
\Upsilon^g(\boldsymbol{\sigma}, T) & \equiv & T_g - g^*
```

?

The [parity implementation](https://github.com/paritytech/parity/blob/master/ethcore/src/executive.rs#L511) seems to be using the refunded amount, ` g*`.

**Comment by pirapira** [comment]
Let me have a read around here.

**Comment by pirapira** [comment]
This seems to be legit to me right now.  Let me further check other clients.

**Comment by pirapira** [comment]
cpp-ethereum does the same as Parity.

**Comment by pirapira** [comment]
Pyethereum does the same as Parity.

**Comment by pirapira** [comment]
Go-ethereum seems to do the same.

**Comment by nicksavers** [comment]
@pirapira @rtkaczyk 
This has been merged into `homestead` and `master`. Any further reason to keep this issue open?

**Comment by pirapira** [comment]
No.  Thanks for noting.
