### ISSUE TITLE
Minimum gas limit different on Ethereum clients?

### ISSUE THREAD

**Issue by ntallar** [ethereum/yellowpaper#317]
[Equation (53)](https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L466) refers to the minimum gas limit for blocks as 125000. Should this value be changed to 5000 (0x1388)? Various Ethereum clients seem to be using that minimum gas limit value:
* *Geth*: https://github.com/ethereum/go-ethereum/blob/master/params/protocol_params.go#L68
* *Parity*: https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/foundation.json#L146

**Comment by pirapira** [comment]
* cpp-ethereum https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/GenesisInfo.cpp#L36

also uses 5000.

**Comment by nicksavers** [comment]
This seems to have been accidentally changed on 16 Feb 2016 in the commit https://github.com/ethereum/yellowpaper/commit/a3381de9e1a20123cddbe85c9d5cc4f01f00d648
The `minGasLimit` was 5000 at Frontier and hasn't changed in any of the hardforks.
