### ISSUE TITLE
Formula 27

### ISSUE THREAD

**Issue by jamesray1** [ethereum/yellowpaper#330]
For the right side of formula 27, here is my understanding of it: take the ith and (i+1)th elements of the keccak-256 hash of x, then get the mod 2048 of those elements. I guess I'm struggling to understand how the formal equations correlate to the statement: "it does this through taking the low-order 11 bits of each of the first three pairs of bytes in a Keccak-256 hash of the byte sequence."

**Comment by pirapira** [comment]
When you also look at the previous formula, for i ∈ {0, 2, 4}, we are looking at [i, i + 1].

We are looking at [0, 1], [2, 3], and [4, 5]. These are the first three pairs, I think.

I think there is a more understandable presentation.

**Comment by jamesray1** [comment]
Yeah I get that, I just don't understand where the "low-order 11 bits" comes from, and I must've read over that section like 10 times.

**Comment by tjayrush** [comment]
I spent a very large time with this. There has to be a "more understandable presentation." I agree wholeheartedly with that.

The "lower 11 bits" part just means take a modulo 2048.  2 raised to 11 is 2048, so looking at the lower 11 bits gives you modulo 2048.

The paris [0,1] [2,3][4,5] are pairs of bytes that you look at as integers which represent (modulo 2048) the bit position to 'twiddle.' (turn on).

For each pair, convert to an integer, x, then modulo by 2048 (so you don't shift past the end of the filter) and then shift a 'true' bit that many positions to the left: (1 << (x % 2048)).

**Comment by jamesray1** [comment]
Thanks for the explanation, it makes sense now.

The part doesn't mention bitwise shifting, but I guess it can be handy to keep in mind how the implementation could work that way.

**Comment by tjayrush** [comment]
Bj(x) is the shift, I guess.

**Comment by jamesray1** [comment]
Current: "it does this through taking the low-order 11 bits of each of the first three pairs of bytes in a Keccak-256 hash of the byte sequence."
Proposal 1: "it does this through taking the low-order 11 bits of each of the first three pairs of bytes in a Keccak-256 hash of the byte sequence.<1 as footnote>" 
Footnote 1. 11 bits = 2^2048. The modulo 2048 of the Keccak-256 hash is the low-order 11 bits.

**Comment by tjayrush** [comment]
I can't tell you how long I spent trying to figure out that exact sentence. Any improvement to that sentence is in improvement indeed (at least in my mind). The whole section probably need improvement, but this helps because the issue you footnoted is what's missing.

**Comment by jamesray1** [comment]
Yeah anything that has to be reread multiple times generally requires editing for clarity.

**Comment by jamesray1** [comment]
https://github.com/ethereum/yellowpaper/pull/344

**Comment by jamesray1** [comment]
Closing because the change is in the above PR.
