### ISSUE TITLE
Can't find SECP-256k1 description by Gura et al. [2004] + other issues for Appendix F

### ISSUE THREAD

**Issue by jamesray1** [ethereum/yellowpaper#335]
Unresolved comments remain:
- [ ] formula 214 equality for secp256k1n is omitted.

I moved most of the original comments to #327 where the changes have been made, except for the below one.

**Comment by jamesray1** [comment]
Also, ‘Electrum style signatures’ should have a reference, e.g. code.vmware.com/sdk/vddk.

**Comment by jamesray1** [comment]
[Here](https://bitcoin.stackexchange.com/questions/21907/what-does-the-curve-used-in-bitcoin-secp256k1-look-like) is info about sec256k1, but it is not an academic-style paper, so it isn't ideal for citing.

**Comment by jamesray1** [comment]
I'm think I'm just going to log all issues on this thread, then make a pull request.

**Comment by jamesray1** [comment]
For formula 214, have a footnote to say that this is FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD036‌ in hexadecimal (which is 78 characters in length, so it is also less than 2^78 = 3.02e23).

**Comment by jamesray1** [comment]
Fix this: https://github.com/ethereum/yellowpaper/pull/345/commits/4710b8efa9f5d6961614b63a181203e800d0a702

**Comment by jamesray1** [comment]
#345

**Comment by pirapira** [comment]
The issue contains many points, many of which have materialized into a PR and requires no further discussion here.  So it's not trivial to see if anything remains to be answered or discussed here.

Suggestion1: open a new issue for each logically independent issue.

Suggestion2: keep a list of open points in the first comment of the issue
* [ ] the definition of SECP-256k1 is not found in the cited reference
* [ ] ...

**Comment by jamesray1** [comment]
Ah, I see that 115792089237316195423570985008687907852837564279074904382605163141518161494337 is not the same as 2^{256} - 2^{32} - 977.

2^256 - 2^32 - 977 = 115 792 089 237 316 195 423 570 985 008 687 907 853 269 984 665 640 564 039 457 584 007 908 834 671 663
