### ISSUE TITLE
|o|>24576 in eqn. 97

### ISSUE THREAD

**Issue by jamesray1** [ethereum/yellowpaper#338]
There doesn't seem to be an explanation near eqn. 97  on p. 9 for why the condition in F exists for |o|>24576. CTRL + F 24576 to find it.

**Comment by jamesray1** [comment]
Note  that  intention is
Note  that  the intention

**Comment by jamesray1** [comment]
I see that o is defined in section 8, para. 2.

**Comment by jwasinger** [comment]
@jamesray1 , I believe that is saying that contract initialization will fail (F) if (|o| > 24576) the created contract is above the maximum size.

**Comment by jamesray1** [comment]
@jwasinger, I understand that it is saying the the output contract code is over 24576 bytes in length, but I want to know why that limit exists, e.g.: to prevent memory getting too bloated, etc.

**Comment by jamesray1** [comment]
Gitter test room chat linked to [this EIP](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md). Consider adding a link to it for an explanation of the limit. E.g.: "for details on why the 24576 byte limit for output contract code exists, refer to this EIP [here](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md)".

**Comment by jamesray1** [comment]
See this commit containing the above suggestion: https://github.com/ethereum/yellowpaper/pull/345/commits/51b0afb3393bce05c7143b60cb80218dc757f56d
