### ISSUE TITLE
Grammar editing e.g. is  proportional  to  smallest  multiple

### ISSUE THREAD

**Issue by jamesray1** [ethereum/yellowpaper#339]
Merged changes into #345. No further issues.

In 9.2 para. 2: " is  proportional  to  smallest  multiple"

 is  proportional  to the smallest  multiple

**Comment by jamesray1** [comment]
δ, the items removed from stack, p. 22 last para.

**Comment by jamesray1** [comment]
0x40
"and we assert the header H can be determined **as its hash is the parent hash** in the block following it."

I'm not sure what this is supposed to mean, but here's a guess:
"and we assert **that** the header H can be determined as its hash, **which** is the parent hash in the block following it."

**Comment by jamesray1** [comment]
For the first two comments: 70c15d5478a00056df3f8ae5af91701826cae212.

I'm not sure what the meaning is supposed to be in the third comment, so I'll leave it until someone else confirms or clarifies.

**Comment by pirapira** [comment]
I think you should be able to create a pull-request using your commit.

**Comment by pirapira** [comment]
No, the third comment means something else, I think.

"and we assert **that** the header H can be determined **because** its hash is the parent hash in the block following it."

Anyway, the sentence is ambiguous and needs clarification.

**Comment by jamesray1** [comment]
Yeah the commit is already part of the pull request that you commented on: https://github.com/ethereum/yellowpaper/pull/345.
