### ISSUE TITLE
Eqn. 131: hard to understand how it works

### ISSUE THREAD

**Issue by jamesray1** [ethereum/yellowpaper#340]
For eqn. 131 on p. 12, I don't think I fully understand how the first line of the piecewise function works. I understand that you want to skip the push function, so add w to i, but why subtract PUSH1 and add 2?

(I've read over 9.4.3 multiple times. I read and understand (or at least I think I do) the push instructions in the appendix H, p. 28, plus the JUMP, JUMPI and JUMPDEST functions defined on the previous page, p. 27.)

**Comment by pirapira** [comment]
Suppose `w` is `PUSH3`.  `PUSH3` is four-byte long, so four need to be added to `i`.

`i + w - PUSH1 + 2` is equal to `i + PUSH3 - PUSH1 + 2`, which is equal to `i + 4`.

**Comment by jamesray1** [comment]
Wait a minute, `PUSH3` is 3 bytes long, right?
On p. 28:
`PUSH1` -> Place a 1-byte item on the stack
`PUSH2` -> Place a 2-byte item on the stack
...
`PUSH32` -> Place a 32-byte item on the stack

So `PUSH3` -> Place a 3-byte item on the stack.

But you want to skip the data of a PUSH instruction, if any, so it needs to be one byte after the code.

Why not just `i + w + 1`? Is that not equal to and a simplified form of `i + w - PUSH1 + 2`?
