### ISSUE TITLE
I don't fully understand 0x3c, 0x39, 0x37, the memory expansion function, and other complex opcodes

### ISSUE THREAD

**Issue by jamesray1** [ethereum/yellowpaper#343]
I understand what they are doing—the maths, but I don't understand why.

For 0x39, I don't understand why I_b, the byte array that is the machine code to be executed, must be less than mu_s[1] + i, which has a maximum upper bound of mu_s[2]-1. Similarly I don't understand why the condition in the first line of the piecewise function in 0x37, and 0x3c is the way that it is. I see that the stack depth of the operation is one more item greater than the stack item in these conditions.

I don't understand the last item in the sequence of the first equation in the logging operations section: mu_s [0] + mu_s[1] - 1, and similarly for the same pattern in the system operation sequences and elsewhere. I read that the memory contents mu_m is a series of zeros of size 2^256 in 9.4.1 para. 1. I think mu_m[mu_s[x], ... , mu_s[y}] is writing to the memory contents the sequence in the square brackets, but I'm not sure, and I think and example of how this works would be helpful. Without understanding how these more fundamental methods work it is harder to fully understand the more complex procedures that they are a part of.

**Comment by jamesray1** [comment]
https://gitter.im/ethereum/yellowpaper?at=59c0b218bc464729744fbc59

> Sorry there was a misunderstanding with what I said:
For formula 0x51, I don't fully understand why the function inputs in the first line are the way they are: it seems like it is the mul of mu_s + i where i = 0 to 31. I understand that a word = 256 bytes = 32 * 8 bits/byte.
From p. 3, first col., last para.:
For subsequences, ellipses are used to specify the intended range, to include elements at both limits, e.g. μm[0..31]denotes the first 32 items of the machine’s memory.

**Comment by jamesray1** [comment]
Closing this and taking to chat for now.

**Comment by pirapira** [comment]
How did you get this statement? " I_b, the byte array that is the machine code to be executed, must be less than mu_s[1] + i"

**Comment by pirapira** [comment]
I found a typo in the description of 0x39 though.  The last argument of M is wrong.

**Comment by pirapira** [comment]
In all of these instructions, the piecewise function is defined like that to say
"When the copied position is before the end of the source, copy that byte from the position.   Otherwise, copy zero."

**Comment by jamesray1** [comment]
> How did you get this statement? " I_b, the byte array that is the machine code to be executed, must be less than mu_s[1] + i"

So in opcode 0x39, CODECOPY, in the first line of the piecewise function, the condition states that mu_s[1]+ 1 < ||I_b||.

**Comment by pirapira** [comment]
The line says "if" before that statement.

**Comment by pirapira** [comment]
So, ||I_b|| might be big enough to satisfy that or not.  Both possibilities exist.

**Comment by jamesray1** [comment]
Yep, I'm all clear on that point, thanks.

**Comment by pirapira** [comment]
It's about "i-th byte that is copied" where the numbers are counted like 0th, 1st, 2nd and so on.

**Comment by jamesray1** [comment]
Sorry, again I am not being clear enough. I was unsure why the last i-th index mu_s[2]-1, but I think it's related to the use of i in the index.

Why is the index up to mu_s[2] - 1? I think it's just designed this way to impose a maximum limit on I_b, "the byte array that is the machine code to be executed", but I'm not sure what exactly the reason for that is.

**Comment by pirapira** [comment]
Why are you writing `- 1`?  It's `- i`.

**Comment by pirapira** [comment]
> Why is the index up to mu_s[2] - 1?

Because `mu_s[2]` specifies the size of the range traversed by `i`s.

**Comment by jamesray1** [comment]
OK. I don't really understand why that is. Maybe I'll get it if I continue reading. I was reading opcode 0xf0, which helps.

**Comment by pirapira** [comment]
The intention of `mu_s[2]` (`mu_s[2]` specifies the size of the range traversed by `i`'s) is not derived from other propositions.  This is desired by somebody somehow, and you will not find the explanation if you continue reading.

**Comment by jamesray1** [comment]
OK, fair enough, just take it at face-value.

**Comment by pirapira** [comment]
Lots of these come from conventions in the past. This one reminds me of

> void *memcpy(void *dest, const void *src, size_t n);

**Comment by jamesray1** [comment]
> void *memcpy(void *dest, const void *src, size_t n);

[Here](https://stackoverflow.com/questions/25060794/writing-memcpy-conformant-with-strict-aliasing#25060988) is a discussion on that.

**Comment by jamesray1** [comment]
I mentioned the above opcodes in this issue: https://github.com/ethereum/yellowpaper/issues/354.

**Comment by jamesray1** [comment]
Anyway, I'm going to call it a day, it's late to be working.
