### ISSUE TITLE
Call gas cost function for DELEGATECALL uses wrong stack indices

### ISSUE THREAD

**Issue by mbrock** [ethereum/yellowpaper#347]
The gas cost function C is defined in H.1 to be equal to C_call(...) when the instruction is either CALL, CALLCODE, or DELEGATECALL.

But the stack indices for CALL and DELEGATECALL are different, because DELEGATECALL doesn't include a value to be transferred.

This means that all the components of the C_call sum that make use of μ_s[2] are incorrect in the case of DELEGATECALL.

Presumably μ_s[2] should be interpreted as 0 in the C_call function for DELEGATECALL, but in fact, μ_s[2] refers to the input offset of the call data.

**Comment by livnev** [comment]
I believe this was fixed with 4db27302163416e19fe8d9d8eb5ad3af6cffe443 and 502dd5fd0e3101556e3a466e57f08528f022188c.
