### ISSUE TITLE
LLL commented out

### ISSUE THREAD

**Issue by jamesray1** [ethereum/yellowpaper#358]
I don't know why this is commented out:
%\section{Low-level Lisp-like Language}\label{app:lll}
%The Low-level Lisp-like Language is a language created in order to efficiently author low-level programs (contracts) without having to resort to EVM-Assembly.

**Comment by pirapira** [comment]
Me neither.  It is not part of the protocol currently.

**Comment by nicksavers** [comment]
This was removed in https://github.com/ethereum/yellowpaper/pull/490
