### ISSUE TITLE
Two R_bs: the block reward of 5 Ether and the Bloom filter

### ISSUE THREAD

**Issue by jamesray1** [ethereum/yellowpaper#359]
These seem like they are different even though they use the same symbol. If I am misunderstood, I think it is due to it being ambiguous.

**Comment by jamesray1** [comment]
Here is the latest build of the PDF in my fork:

https://archive.org/details/Ethereum_Yellow_Paper_201709

It is handy because with `hyperref` I've added cross-references.

**Comment by jamesray1** [comment]
Yeah this should be changed, it's confusing.

**Comment by jamesray1** [comment]
They look exactly the same, but are different.

**Comment by jamesray1** [comment]
#576

**Comment by pirapira** [comment]
The PR was merged.
