### ISSUE TITLE
The Yellow Paper allows future blocks, but is it intended or not?

### ISSUE THREAD

**Issue by wlzla000** [ethereum/yellowpaper#364]
According to [_the Yellow Paper_](http://yellowpaper.io/), the restrictions on block timestamps, H<sub>s</sub>, are,

 - H<sub>s</sub> ∈ ℙ<sub>256</sub> (Mathematical term <sup>#</sup>35) ― ①,
 - and H<sub>s</sub> > P(H)<sub>H<sub>s</sub></sub> (Mathematical term <sup>#</sup>48 and <sup>#</sup>56) ― ②,

where P(H)<sub>H<sub>s</sub></sub> is the parent (previous) block's timestamp, and ℙ<sub>256</sub> is a set of natural numbers less than 2<sup>256</sup>.

It seems [_the Yellow Paper_](http://yellowpaper.io/) allows _future blocks_ (blocks that have a future timestamp) ― ③, as there's no restriction apart from ① and ②.

Is it (③) intended, or is it an error on [_the Yellow Paper_](http://yellowpaper.io/)?
If latter, it would cause **_Consensus problem_** between the implementations and should be fixed quickly.

If there's something I missed or was wrong above, please let me know.

<sub>This is asked also [here](https://ethereum.stackexchange.com/questions/27485/how-do-ethereum-clients-cope-with-future-blocks).</sub>

**Comment by tjayrush** [comment]
The restriction here is that the current block's timestamp must be at least its parent's timestamp plus one second. It doesn't imply anything about how far in the future it is as far as I can see.

**Comment by wlzla000** [comment]
Yes, and that's exactly what I understood.
What I want to ask is whether it is intended (so not a problem) or not.

**Comment by wlzla000** [comment]
I'm curious about how _geth_ and _eth_ implemented it. Do they really accepts **any** _future blocks_ as _the Yellow Paper_'s one?

**Comment by wlzla000** [comment]
Done. [I read the source code of _Eth_, _Geth_, _Parity_, _pyethapp_.](https://github.com/wlzla000/understanding-ethereum/blob/master/Ethereum/FutureBlockHandling.md)
- _Eth_ keeps _future blocks_ (in `m_future` map object) and later process them at the time specified in the timestamp.
- _Geth_ and _Parity_ accept _future blocks_, but only maximum 30 seconds future ones. Otherwise, discard. _So clever._

If they were naïve clients, so implemented the block timestamp validation with only the restrictions on _the Yellow Paper_, they would have integer overflow vulnerabilities lead to DoS. :)
