### ISSUE TITLE
[Nitpick] Section 7.1 is Misleading

### ISSUE THREAD

**Issue by jwasinger** [ethereum/yellowpaper#391]
```
7.1. Subtleties. Note that while the initialisation code
is executing, the newly created address exists but with no
intrinsic body code.
```

This would imply that a contract which calls `CODESIZE` during its own initiation should expect the result to be 0 (which is not the case on any clients AFAIK).  We had a question related to this in the tests gitter room that led to some confusion on my part.  @pirapira I think it would be appropriate to add a footnote here to clarify the behavior of `CODESIZE` and `CODECOPY` during contract initiation.  

Would you accept a PR for this?

**Comment by pirapira** [comment]
Yes, that's a good idea.  I'll do it.
