### ISSUE TITLE
Eq. 136: unbalanced bracket and parenthesis. Typo or intentional?

### ISSUE THREAD

**Issue by petefarmer** [ethereum/yellowpaper#395]
[YellowPaper-eq134 (2).pdf](https://github.com/ethereum/yellowpaper/files/1487796/YellowPaper-eq134.2.pdf)

Grateful to whomever can explain the attached expression or validate it as a typo.

Ignore the eq 134 number in the filename... it's eq 136 in the latest build.

**Comment by fulldecent** [comment]
Intentional, that is a half-open range.

**Comment by petefarmer** [comment]
@fulldecent thank you for answering! It all makes sense now.
