### ISSUE TITLE
time sync

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/yellowpaper#46]
What if a malicious miner puts a very high timestamp in his block header. The block should still be valid, since the only condition in the YP is timestamp > timestamp of parent block.  Now he can continue to mine with his wrong clock and all the other miners will always fail on this condition. What is the current solution to this problem? Is it enough to specifiy something in the network protocol for time syncing between peers, or do we need to have something in the YP?

**Comment by gavofyork** [comment]
YP only specifies the formal requirements. The game theory over which chain to mine on and when is left as an exercise to the reader. FWIW, the decision is based around your expectation of mining a new block on an old chain before you would be able to begin mining on the chain ending in a block with future time.
