### ISSUE TITLE
uncles list order

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/yellowpaper#47]
Is it important to define the order of the uncle list? Right now the unclesHash in the block header is defined as "The Keccak 256-bit hash of the uncles list portion of this block; formally H_u.". Later int Eq. 27 it is stated: "H_u ≡ KEC(RLP(L*_H(B_U)))" But the order in B_U is not defined.

**Comment by gavofyork** [comment]
though arbitrary, it is definite within the block, and so at this point, well-defined.
