### ISSUE TITLE
Create PDFs for each version, and put it in each branch, or as a link.

### ISSUE THREAD

**Issue by jamesray1** [ethereum/yellowpaper#508]

**Comment by nicksavers** [comment]
The build process is available for everyone downloading the source.
I don't see the need to maintain hosting for all older versions.

**Comment by jamesray1** [comment]
It would be good to at least have a link for Frontier for convenience, as the other releases are defined in the EIPs, while Frontier isn't. It doesn't necessarily need to be hosted, but could just be a link to the file in the branch. I don't think the Frontier version needs to be updated, so it's not like you need to have an automatic build to a link.
