### ISSUE TITLE
Online version

### ISSUE THREAD

**Issue by Latrasis** [ethereum/yellowpaper#53]
Hi Gav,

Here's an online version for people to more quickly read: https://github.com/Latrasis/yellowpaper/tree/gh-pages
Using Mathjax to render the Latex and Gh-pages for hosting.

A Gh-Pages branch on the master is needed to start a pull request.

Thanks

**Comment by chriseth** [comment]
Nice! It has some issues with tables, which was to be expected, I guess, but it also does not render inline math. Can that be changed?

**Comment by CJentzsch** [comment]
Whats wrong with http://gavwood.com/paper.pdf? It is always up to date and you only need to open a link indtead of compiling anything.

**Comment by chriseth** [comment]
Hm, this fact could perhaps mentioned in a README file. I was not aware that it is updated automatically.

**Comment by Latrasis** [comment]
We can then just add http://gavwood.com/paper.pdf on the readme?
Well that makes everything *much easier* now lol.

**Comment by axic** [comment]
Probably this issue could be closed.
