### ISSUE TITLE
m should mean {B_H}_c?

### ISSUE THREAD

**Issue by janx** [ethereum/yellowpaper#56]
This equation: https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L578

The right side should be coinbase addr?

**Comment by pirapira** [comment]
Now the `master` branch has changed, the link does not lead to the equation.  The equation was around here: https://github.com/ethereum/yellowpaper/blob/14f53cac472e99bdf91154f8be7f03245beca613/Paper.tex#L578

**Comment by pirapira** [comment]
By now this has been fixed as suggested. fedf10d125ef4cd53585098576924e1aa0aec5e0
