### ISSUE TITLE
Question on total gas used euation

### ISSUE THREAD

**Issue by janx** [ethereum/yellowpaper#57]
https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L589

Here the total used gas is defined to `g_0` plus `g'`, but `g'` is defined to 'gas remaining', is this a typo?

**Comment by pirapira** [comment]
Now `master` branch has changed, and the link does not point to the equation.  The equation was here https://github.com/ethereum/yellowpaper/blob/14f53cac472e99bdf91154f8be7f03245beca613/Paper.tex#L589

**Comment by pirapira** [comment]
The equation has been fixed as suggested b9b1ee8671dd9469e3b4ebca6246b6f8e3d1b62d
