### ISSUE TITLE
Inconsistent usage of account subscript b

### ISSUE THREAD

**Issue by janx** [ethereum/yellowpaper#58]
https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L188

It says sigma[a]_b is account balance.

https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L628

Here sigma[a]_b represents body code of account b.

**Comment by pirapira** [comment]
The master branch has changed, and the links do not point to the equations anymore.  They were at around
https://github.com/ethereum/yellowpaper/blob/14f53cac472e99bdf91154f8be7f03245beca613/Paper.tex#L188

and 

https://github.com/ethereum/yellowpaper/blob/14f53cac472e99bdf91154f8be7f03245beca613/Paper.tex#L628

**Comment by pirapira** [comment]
At line 628, I don't see sigma[a]_b representing the body code.  It looks like representing the balance.  I might be looking at wrong equations.

**Comment by fulldecent** [comment]
I have reviewed and found these variable names have been changed.

> `resultant state $\boldsymbol{\sigma}^{**}$, available gas remaining $g^{**}$, the accrued substate $A$ and the body code of the account $\mathbf{o}$.`

This issue can be safely closed now

**Comment by pirapira** [comment]
@fulldecent thank you for checking.
