### ISSUE TITLE
Include a version with a white background

### ISSUE THREAD

**Issue by fulldecent** [ethereum/yellowpaper#580]
This will be easier to read in printed form.

**Comment by pirapira** [comment]
Yes, I noticed lots of yellow inks are consumed.  Maybe a command line option to `./build.sh` is the first step.

**Comment by fulldecent** [comment]
Here is the output, PR coming.

[Paper b9ee254 - 2018-02-12.pdf](https://github.com/ethereum/yellowpaper/files/1717599/Paper.b9ee254.-.2018-02-12.pdf)
