### ISSUE TITLE
Question on exceptional halting

### ISSUE THREAD

**Issue by janx** [ethereum/yellowpaper#61]
https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L855

In the paragraph below definition 110, it says 'if a CALL, CALLCODE or CREATE instruction is executed when the call stack limit of 1024 is reached'. Which part of definition 110 does it correspond?

And it's also hard to understand 'The astute reader will realise that this implies that no instruction can, through its execution, cause an exceptional halt.' Will JUMP to invalid destination cause an exceptional halt?

**Comment by pirapira** [comment]
The link pointed to https://github.com/ethereum/yellowpaper/blob/5a78caaf6a499382926ed8fba6d62d21ca98fd6f/Paper.tex#L855 originally.

The first question: the sentence has been modified.  Now the limit on the usual stack (of words) is mentioned.

The second question: This sentence says exceptional halts do not occur in the `O()` function.   JUMP to invalid destination makes the `Z` function True, so `O()` is not called.

@janx please close the issue if these answers are OK.

**Comment by janx** [comment]
@pirapira looks good, thanks!
