### ISSUE TITLE
Typo in is-kin definition

### ISSUE THREAD

**Issue by janx** [ethereum/yellowpaper#62]
https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L973

Here should be `k(U, P(H), n-1)` to form recursion?

**Comment by janx** [comment]
https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L1044

Another type, should be `{R}[n]_l`.

**Comment by pirapira** [comment]
These have been fixed.

https://github.com/ethereum/yellowpaper/commit/1bd23789016dd4cc3bbb81ef5b8e3685035c05a0

https://github.com/ethereum/yellowpaper/commit/dce5332f95539d0237b0ffbde6ef01ada87cbb5e
