### ISSUE TITLE
Should the yellow paper specify chain ID?

### ISSUE THREAD

**Issue by pirapira** [ethereum/yellowpaper#662]
@jamesray1 on Gitter:
>  I notice that the chain_ID is not actually specified in the Yellow Paper, which I believe that it should be. @pirapira, would you agree?

**Comment by jamesray1** [comment]
https://gitter.im/ethereum/yellowpaper?at=5a9b73340a1614b712dbdf53

**Comment by jeemud** [comment]
I think chains keep on adding so no need to add those in yellow paper. Just its enough mentioning how to  specify chain id in Tx ( Appendix F. Signing Transactions - ) 288 (Tw, Tr, Ts) = ECDSASIGN(h(T), pr ) 
Tw is either the recovery identifier or ‘chain identifier doubled plus 35 or 36’. In the second case, where v is the chain
identifier doubled plus 35 or 36, the values 35 and 36 assume the role of the ‘recovery identifier’ by specifying the parity
of y, with the value 35 representing an even value and 36 representing an odd value.
