### ISSUE TITLE
EXTCODESIZE definition

### ISSUE THREAD

**Issue by DanielRX** [ethereum/yellowpaper#667]
In the OPCODE section, EXTCODESIZE is defined as the norm of the codeHash, not the code itself.

`||\sigma[a]_c||` is used instead of  `||b||` where `KEC(b) = \sigma[a]_c`

**Comment by yperbasis** [comment]
Fixed by https://github.com/ethereum/yellowpaper/commit/cf5aafcd20459bee7850521a18644e54480384f2
