### ISSUE TITLE
The Yellow Paper may need to be completely rewritten with Ethereum 2.0, and the EVM is abstracted so a spec may need not be followed exactly.

### ISSUE THREAD

**Issue by jamesray1** [ethereum/yellowpaper#675]
https://ethresear.ch/t/sharding-phase-1-spec/1407/

**Comment by nicksavers** [comment]
Perhaps. So when the time comes, it could be separate the abstracted parts into a separate document. Similar to the separated (unfinished) `Wire.tex` and `JS.tex`.
