### ISSUE TITLE
Bloom Filter Implementations Differ from Yellow Paper

### ISSUE THREAD

**Issue by AusIV** [ethereum/yellowpaper#690]
Recently I've been working on an Ethereum client independent tool that inspects the bloom filter to determine whether to request transactions from the Ethereum client for a given block. In the process I discovered that, for the same transaction receipt with the same topics, go-ethereum and ethereumjs-vm were generating different bloom filters. My initial assumption was that, because go-ethereum is used regularly on mainnet, while ethereumjs-vm is used for testing and simulations, that ethereumjs-vm must be out of compliance with the yellow paper. However, reading through the yellow paper, I've come to believe that go-ethereum (and presumably other in-production Ethereum clients) are out of compliance with the yellow paper.

The yellow paper says that a topic is 32 bytes, and defines `m(x, i) ≡ KEC(x)[i, i + 1] mod 2048`. If `x` in this equation is a topic, then it follows that `x` should be 32 bytes. This is consistent with the ethereumjs-vm implementation.

In go-ethereum, however when something is [added to a bloom filter](https://github.com/ethereum/go-ethereum/blob/master/core/types/bloom9.go#L60), it is converted to a big integer and then back to bytes before applying `KEC`. This means that if the topic has leading zero bytes, it gets trimmed to the number of bytes necessary to represent the integer value, effectively stripping away any null bytes. I don't see anything in the yellow paper that indicates that leading zero bytes should be stripped away, but given that Geth does so and manages to maintain consensus with the other Ethereum clients, it seems that this is at least a defacto standard for maintaining bloom filters.

Am I missing something in the yellow paper, or are the current implementations inconsistent with the yellow paper?

**Comment by tjayrush** [comment]
X is bytes so leading zero are insignificant. When it gets encoded to RLP it's prepended with leading zeros to bring it to 32 bytes long.

**Comment by AusIV** [comment]
I don't see any indication that it's supposed to be RLP encoded before KEC is used to calculate the hash for insertion into the bloom filter, and none of the bloom filter implementations do so. Leading zeroes are certainly significant to Keccac, which makes them significant to the output of the bloom filter.

**Comment by axic** [comment]
@pirapira what do you think?

**Comment by AusIV** [comment]
This was my misunderstanding of Geth's code. It looks like bloom.Add() and bloom.Test() aren't used in any consensus critical places, and that the actual construction and testing of bloom filters implements according to the Yellow Paper.

**Comment by AusIV** [comment]
I've raised an issue with Geth about this here: https://github.com/ethereum/go-ethereum/issues/18092
