### ISSUE TITLE
output of BYTE instruction should be on least significant byte

### ISSUE THREAD

**Issue by thomas-huet** [ethereum/yellowpaper#729]
According to the current definiton, the instruction BYTE sets the most significant byte.
However implementations set the least significant byte (which makes more sense):
https://github.com/ethereum/go-ethereum/blob/33d233d3e18359123993d3f54987441290faf212/core/vm/instructions.go#L291
https://github.com/ethereum/aleth/blob/ec3886029393fc9927b130ba8f8671480d810391/libaleth-interpreter/VM.cpp#L728
https://github.com/paritytech/parity-ethereum/blob/7c335e87642b848f61ab3ee7bbff5964b53d6f11/ethcore/evm/src/interpreter/mod.rs#L1001

**Comment by livnev** [comment]
@thomas-huet I'm not sure: I believe the implementations agree with the yellow paper. For example in `aleth`:
```
m_SPP[0] = m_SP[0] < 32 ? (m_SP[1] >> (unsigned)(8 * (31 - m_SP[0]))) & 0xff : 0;
```
so if the first stack argument is 0, the second stack argument is shifted right by 248 bits (and the last byte masked). This gives the most significant bit, not the least.

Also worth comparing with KEVM, see the definition of `BYTE` [here](https://github.com/kframework/evm-semantics/blob/e2f6dffa3cf861a7d9b23a8699dc97f1cae97e7d/evm.md#expressions) and the definition of `byte(N, W)` [here](https://github.com/kframework/evm-semantics/blob/master/data.md#bitwise-operators). It is likewise counting starting with the MSB.

**Comment by hacker-DOM** [comment]
@livnev I think you mistook getting a byte vs. setting a byte (pushing the result onto the stack). I think @thomas-huet 's original issue is valid. Creating a new issue for visibility.

**Comment by livnev** [comment]
@hacker-DOM Indeed, I think I mistook the issue to be about which byte was being indexed in the input vs. where it was being put in the output. The latter is what seems to be the real issue in the paper. My bad.
