### ISSUE TITLE
GasLimit field type different on Ethereum clients?

### ISSUE THREAD

**Issue by mmrozek** [ethereum/yellowpaper#750]
[Equation 37](https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L451) refers that `gasLimit` should be a natural number. Why couldn't it be bound to N256?

I am confused because various Ethereuem clients implement this field in different ways:
- Parity: https://github.com/paritytech/parity-ethereum/blob/master/ethcore/types/src/header.rs#L79
- Geth: https://github.com/ethereum/go-ethereum/blob/master/core/types/block.go#L80

**Comment by nicksavers** [comment]
Not limiting the `gasLimit` allows it to be as high as needed without a hard fork. However current hardware can't even process gas higher than 2^32, so clients don't need to support N256 yet.

**Comment by nicksavers** [comment]
Keep an eye on https://github.com/ethereum/EIPs/issues/106 and https://github.com/ethereum/EIPs/pull/1985.
