### ISSUE TITLE
incorrect input layout in BN_MUL definition

### ISSUE THREAD

**Issue by livnev** [ethereum/yellowpaper#751]
The layout of the input data to the `BN_MUL` zk-SNARK precompile is incorrect. Currently, it looks like this:

![screenshot620](https://user-images.githubusercontent.com/3964494/57608112-4d906980-7564-11e9-8a62-87c66712e7c8.png)

which means that the first 32 bytes of the input memory range are occupied by the scalar `n`, and the next 64 bytes are occupied by the curve point. In fact, according the Ethereum test suite and to other implementations like `aleth`, `parity`, and KEVM, the first 64 bytes are the curve point and the next 32 are the scalar, so it should look like this:

![screenshot621](https://user-images.githubusercontent.com/3964494/57608931-d3f97b00-7565-11e9-8f15-4f45f9968ee4.png)

*correct implementation references:*
- [aleth](https://github.com/ethereum/aleth/blob/32f9c88f65fc30d7b682de651e2d40d8b7e26078/libdevcrypto/LibSnark.cpp#L192)
- [parity](https://github.com/paritytech/parity-ethereum/blob/2cf0d7d7757829a8d6d3a65547c96258c73b9b91/ethcore/src/builtin.rs#L467)
- [KEVM](https://github.com/kframework/evm-semantics/blob/master/evm.md#precompiled-contracts)
```
    syntax PrecompiledOp ::= "ECMUL"
 // --------------------------------
    rule <k> ECMUL => #ecmul((#asWord(DATA [ 0 .. 32 ]), #asWord(DATA [ 32 .. 32 ])), #asWord(DATA [ 64 .. 32 ])) ... </k>
         <callData> DATA </callData>
```

**Comment by livnev** [comment]
@nicksavers

**Comment by nicksavers** [comment]
Thanks for the reminder. I missed this one.
Also my compliments for the excellent documentation on your change request.

**Comment by livnev** [comment]
@nicksavers thanks for the review 👍
