### ISSUE TITLE
Gas cost of ECPAIRING is incorrect 

### ISSUE THREAD

**Issue by livnev** [ethereum/yellowpaper#759]
The yellow paper specifies the gas cost of `ECPAIRING` as 60,000k + 40,000, where `k` is the number of pairs of curve points to check. In reality, it should be 80,000k + 100,000. This is confirmed by cross-referencing with the following implementations:

[KEVM has](https://github.com/kframework/evm-semantics/blob/ffd9552f3703c0a60b6b3e2262b9430e2764e2f8/evm.md#execution-gas):
```
rule <k> #gasExec(_, ECPAIRING) => 100000 +Int (#sizeWordStack(DATA) /Int 192) *Int 80000 ... </k> <callData> DATA </callData>
```

[py-evm has](https://github.com/ethereum/py-evm/blob/814fb0e2d3dccf16225a8c8aadef579f7c9265f6/eth/constants.py#L98)
```
GAS_ECPAIRING_BASE = 100000
GAS_ECPAIRING_PER_POINT = 80000
```

[aleth has](https://github.com/ethereum/aleth/blob/697f1fb6a606f6c9d55d08f6a91e03ed8676b968/libethcore/Precompiled.cpp#L202)
```
ETH_REGISTER_PRECOMPILED_PRICER(alt_bn128_pairing_product)(bytesConstRef _in)
{
	return 100000 + (_in.size() / 192) * 80000;
}
```

[parity has](https://github.com/paritytech/parity-ethereum/blob/master/ethcore/res/ethereum/foundation.json)
```
		"0x0000000000000000000000000000000000000008": {
			"builtin": {
				"name": "alt_bn128_pairing",
				"activate_at": "0x42ae50",
				"pricing": {
					"alt_bn128_pairing": {
						"base": 100000,
						"pair": 80000
					}
				}
			}
		},
```

**Comment by nicksavers** [comment]
Good catch
