### ISSUE TITLE
G_quaddivisor is incorrect (should be 20)

### ISSUE THREAD

**Issue by livnev** [ethereum/yellowpaper#762]
The yellow paper defines `G_quaddivisor` to be 100. In reality, it is 20.

[KEVM has](https://github.com/kframework/evm-semantics/blob/master/evm.md#default-schedule):

```
rule Gquaddivisor < DEFAULT > => 20
```

[py-evm has](https://github.com/ethereum/py-evm/blob/814fb0e2d3dccf16225a8c8aadef579f7c9265f6/eth/constants.py#L169):

```
GAS_MOD_EXP_QUADRATIC_DENOMINATOR = 20
```

[aleth has](https://github.com/ethereum/aleth/blob/697f1fb6a606f6c9d55d08f6a91e03ed8676b968/libethcore/Precompiled.cpp#L184)
```
return multComplexity(maxLength) * max<bigint>(adjustedExpLength, 1) / 20;
```

**Comment by karalabe** [comment]
If this is the same as https://eips.ethereum.org/EIPS/eip-198, then 20 seems to be the correct one.
