### ISSUE TITLE
How are externally owned accounts created?

### ISSUE THREAD

**Issue by lukwue** [ethereum/yellowpaper#774]
Hello,

I have read that an account is created by generating a public and private key-pair. This would be totally locally, so no update on the blockchain would be necessary.

However, in the yellow paper it says, that accounts have an associated balance which is stored on the network. 

But when I locally generate such a pair, the blockchain is not modified and so I do not have an account yet. Does this mean, the balance of an address is first recorded when the address receives money?

I guess so but unfortunately I couldn't find a reliable source stating that which I need for my bachelor thesis.

Am I correct and if, can anyone supply me with a source? 

Thank you :)

**Comment by acoglio** [comment]
It looks like the paragraph after equation (99), "Throughout the present work, ...", may provide a confirmation of that. This is under the 'Message Call' section, but note that Section 4.2 says that a transaction results in a message call if it doesn't result in the creation of a contract.

**Comment by lukwue** [comment]
OK, thanks. I also found another source on [Ethereum's homepage](https://ethereum.org/en/developers/docs/accounts/).
