### ISSUE TITLE
Missing CHAINID opcode (EIP-1344)

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/yellowpaper#784]
The yellow paper is presently missing the CHAINID opcode (`0x46`) from the description of the EVM. This opcode was introduced in EIP-1344, which is final and has been implemented on mainnet

https://eips.ethereum.org/EIPS/eip-1344

**Comment by protolambda** [comment]
This is still an open issue, I couldn't find it in the yellow paper while auditing some L2 protocol code.
