### ISSUE TITLE
Typo in equation 63

### ISSUE THREAD

**Issue by Kipitup** [ethereum/yellowpaper#807]
Hello,

Not a huge problem, but I think there are 2 typos in the equation 63 on the _6.2 execution_ part.
The 'to' address for the transaction (T_t_) and the transaction value (T_v_) is included twice in the tuple.

![Capture d’écran 2021-06-21 à 15 17 45](https://user-images.githubusercontent.com/33808300/122776425-632bfd80-d2ab-11eb-9285-0ec9e6de5729.png)

Thanks

**Comment by yperbasis** [comment]
Those are not typos: please see the definition of Theta in section 8 "Message Call", Equation (102).

**Comment by Kipitup** [comment]
Indeed, thanks for the help :)

I'm closing the issue.
