### ISSUE TITLE
Can the sender of a message call be an empty account?

### ISSUE THREAD

**Issue by hacker-DOM** [ethereum/yellowpaper#832]
The Yellow Paper contains the following logic under message call:

<img width="509" alt="Screenshot 2021-12-06 at 8 16 51 PM" src="https://user-images.githubusercontent.com/18601956/144916049-7b9466be-bb11-47c7-b80b-7c6ae552e703.png">

If the message call is due to a contract, it must have code, hence it is not an empty account. If the message call is due to a transaction, then the nonce is at least 1 (see below under Transaction Execution)  so the account cannot be empty..

<img width="526" alt="Screenshot 2021-12-06 at 8 19 11 PM" src="https://user-images.githubusercontent.com/18601956/144916367-5759f2b5-6d93-4a3b-a7bd-5a9fe26b367b.png">

Is there a case when the first case of Figure 1 is applicable?

**Comment by yperbasis** [comment]
Transaction sender might be an empty account; see PR #822.

**Comment by hacker-DOM** [comment]
Interesting. I'm guessing this is because in the past there was different logic for nonce incrementing? (Because as of the current logic of the Yellow Paper, the nonce get incremented _before_ equation (109).)
