### ISSUE TITLE
Is second case of `C_gascap` reachable?

### ISSUE THREAD

**Issue by hacker-DOM** [ethereum/yellowpaper#834]
The Yellow Paper specifies under Execution Model

<img width="548" alt="Screenshot 2021-12-08 at 6 28 20 PM" src="https://user-images.githubusercontent.com/18601956/145263582-827204a0-b3da-4a9a-9b53-8e0bcd0c437a.png">

However, under CALL:

<img width="819" alt="Screenshot 2021-12-08 at 6 29 11 PM" src="https://user-images.githubusercontent.com/18601956/145263724-4970a934-e9d9-4c8a-be5c-2158f728f497.png">

It seems to me the second case of `C_gascap` cannot occur.

Clearly `C_gascap >= 0`. Hence `C_call >= C_extra`. If `mu_g < C_extra`, then `mu_g < C_call`, so `mu_g < C(sigma, mu, A, I)` and hence there would be an exception due to Figure 1 before `CALL` gets executed.

What am I doing wrong?

**Comment by yperbasis** [comment]
It might be not reachable during a successful execution, but the cost function has to be defined for all cases, in particular for the gas check in Eq (145). If you remove the second case in `C_gascap`, the cost of the call instruction will be undefined in certain situations.

**Comment by hacker-DOM** [comment]
That makes sense, ty!
