### ISSUE TITLE
Typo in exceptions regarding state changes

### ISSUE THREAD

**Issue by SergioDemianLerner** [ethereum/yellowpaper#84]
"Like the out-of-gas (OOG) exception, they not leave state changes intact."

Shouldn't it be ?
"Like the out-of-gas (OOG) exception, they leave the state intact"

**Comment by axic** [comment]
I think the first implies that "state changes applied" are not "left intact", i.e. they are *changed*. 

The second option is way clearer in my opinion.

**Comment by fulldecent** [comment]
Agreed. Added a PR.

**Comment by nicksavers** [comment]
Neither is really correct, the state is not left in tact.
