### ISSUE TITLE
EVM code hash no longer immutable?

### ISSUE THREAD

**Issue by softwareplumber** [ethereum/yellowpaper#868]
Is this strictly true any more?

> The hash of the EVM code of this account---this is the code that gets executed should this address receive a message call; it is 
> immutable and thus, unlike all other fields, cannot be changed after construction

"cannot be changed after construction" - unless the contract is destroyed and re-initialized with CREATE2

There are so many potential security issues associated with assuming the contract code associated with an account is _actually_ immutable that I believe it is unwise to leave this as it stands. Should the second clause be deleted?

**Comment by yperbasis** [comment]
Yes, you're right. I'll remove the immutability clause.
