### ISSUE TITLE
The accrued state after an unexceptional but aborted `to_address` of a CALL

### ISSUE THREAD

**Issue by OlivierBBB** [ethereum/yellowpaper#910]
- [Description](#description)
   * [In the Yellow paper](#in-the-yellow-paper)
   * [In EIP-2929](#in-eip-2929)
   * [In the execution specs](#in-the-execution-specs)
   * [In Besu](#in-besu)
- [Solution](#solution)

<a name="description"></a>
# Description

This issue is a follow-up on [an issue documented on the execution-specs repo](https://github.com/ethereum/execution-specs/issues/978). There seems to be a discrepancy between the yellow paper and the aforementioned implementation when it comes to updating the accrued state $A$ when a CALL-type instruction
- raises no exception
- but is aborted in the sense that either
  - the instruction attempts to transfer more value than the current balance allows for or
  - the current frame has call stack depth  1024

<a name="in-the-yellow-paper"></a>
## In the Yellow paper

The latest version of the Yellow Paper (Yellow paper `PARIS VERSION 71beac3`), as well as all versions stretching back at least to London, sees the accrued state unmodifed in the case described above i.e. in the _otherwise_ case depicted below

<img width="1535" alt="image" src="https://github.com/user-attachments/assets/9f54cfcd-6147-4849-840b-ca32e9577b8b">

In the "_otherwise_ case" the new accrued substate $A'$ would be $A$, the accrued substate prior to processing the CALL-type instruction, is just the original accrued substate, i.e. $A' = A$.

<a name="in-eip-2929"></a>
## In EIP-2929

Yet [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929) suggests that one should have $A' = A ^ *$. See the following paragraph

<img width="1049" alt="image" src="https://github.com/user-attachments/assets/c6d53d69-7a7e-454f-897b-6ecda417b536">

This is what I understand to be implemeted in the execution specs (see the two links below) and in Besu as well (see link below.) Also this interpretation (warm the address regardless of whether or not the EVM 'enters' the CALL) makes intuitively more sense. Indeed the CALL pricing takes into account the cost of warming the recipient. Since we are considering the unexceptional case there will be no out of gas exception and the full price of the CALL instruction (modulo the possible $G_\text{callstipend}$ immediate gas refund) will be deducted from the available gas and execution will continue in the current context. It only makes sense that the address which one paid the warming of should remain warm after the aborted CALL-type instruction.

<a name="in-the-execution-specs"></a>
## In the execution specs

The relevant code snippet from the execution specs
- unconditional warming of `to_address` ... https://github.com/ethereum/execution-specs/blame/c854868f4abf2ab0c3e8790d4c40607e0d251147/src/ethereum/cancun/vm/instructions/system.py#L361
- ... which is followed by checking for the "insufficient balance" aborting condition https://github.com/ethereum/execution-specs/blame/c854868f4abf2ab0c3e8790d4c40607e0d251147/src/ethereum/cancun/vm/instructions/system.py#L384

The above also effectively implements $A' = A ^ *$ in the unexceptional yet aborted case.

<a name="in-besu"></a>
## In Besu

relevant code snippet from Besu
- unconditional prewarming of `to_address` ... https://github.com/hyperledger/besu/blob/76a3df704efa1d597976e20a91cb3b532f0f639f/evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCallOperation.java#L182
- ... which is followed by checking for aborting conditions ("insufficient balance" or "max call stack depth reached") https://github.com/hyperledger/besu/blob/76a3df704efa1d597976e20a91cb3b532f0f639f/evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCallOperation.java#L197

Again, the above also effectively implements $A' = A ^ *$ in the unexceptional yet aborted case.

<a name="solution"></a>
# Solution

If the above interpretation is correct then the fix would be trivial: in the _otherwise_ case replace the returned value by

$$(\sigma, C_\textrm{CALLGAS}(\sigma, \mu, A), A ^ *, 0, ())$$

![image](https://github.com/user-attachments/assets/fbc3b63b-8159-47ef-aeac-5261928bac47)

**Comment by yperbasis** [comment]
Thank you! Fixed by PR #913

**Comment by OlivierBBB** [comment]
Thanks @yperbasis. Is it possible to make PR's to this repo or should one fork it ? I may have missed it but I have not found documentation relative to contributing.

**Comment by yperbasis** [comment]
> Thanks @yperbasis. Is it possible to make PR's to this repo or should one fork it ? I may have missed it but I have not found documentation relative to contributing.

You have to fork this repo to make a PR.
